FROM ubuntu:22.04 #change this as needed, look at docker repos

# No interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install app dependencies
RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    ca-certificates \
    build-essential \
    git \
    vim \
    python3 \
    python3-pip \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy your requirements file 
COPY requirements.txt .

# Install Python libraries
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy any other files you need
# COPY . .

# Initiate bash shell when starting 
CMD ["bash"]
