FROM ubuntu:22.04

# No interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install app dependencies
RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    ca-certificates \
    build-essential \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Set directory for Miniconda
ENV CONDA_DIR=/opt/conda

RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -u -p $CONDA_DIR && \
    rm /tmp/miniconda.sh

ENV PATH=$CONDA_DIR/bin:$PATH


# Copy environment.yml into your container
COPY environment.yml /tmp/environment.yml

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

# Create the environment
RUN conda env create -f /tmp/environment.yml

# Autoload environment, change the environment name to what your environment is named
ENV CONDA_DEFAULT_ENV=environment
ENV PATH=$CONDA_DIR/envs/environment/bin:$PATH

# Set workspace
WORKDIR /workspace

# Load any github repos if necessary
# RUN git clone https://github.com/user/repo.git

CMD ["bash"]


