Universe   = container
container_image = docker://lsvaren/transformers
Executable = run_script.sh
transfer_input_files = train_model_tutorial_1.py,tutorial_1_inputs

should_transfer_files = YES
when_to_transfer_output = ON_EXIT


request_gpus = 1
request_cpus = 1
request_memory = 25 GB
request_disk = 40 GB
+WantGPULab = true
+WantFlock = true


batch_name = tutorial_1
output = $(Cluster).out
error = $(Cluster).err
log = $(Cluster).log

queue 
